# tox (https://tox.readthedocs.io/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

# <Linux, default>   pyinstaller --windowed --onefile --add-binary "serial.png:." SerialPortIdentifier.py \
# <Windows> pyinstaller --windowed --onefile --add-binary "serial.png;." SerialPortIdentifier.py \

[tox]
envlist = py39
skipsdist = true

[testenv]
deps=-r{toxinidir}/requirements.txt

commands=
   python -c "import sys; sep=';' if sys.platform == 'win32' else ':'; print(f'pyinstaller --windowed --onefile --add-binary \"serial.png{sep}.\" SerialPortIdentifier.py')"
   pyinstaller --windowed --onefile --add-binary "serial.png{env:PYINSTALLER_SEP:;}" SerialPortIdentifier.py
